# Generated by Django 3.2.8 on 2021-11-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.CharField(max_length=60),
        ),
    ]
