# Generated by Django 2.2.12 on 2021-11-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211108_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='product',
        ),
    ]
