# Generated by Django 2.2.12 on 2021-11-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_subscription_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
