# Generated by Django 2.2.12 on 2021-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='quantity',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_id',
            new_name='address_2',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='product',
        ),
        migrations.AddField(
            model_name='subscription',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='country',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
