# Generated by Django 3.2.8 on 2021-10-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
