# Generated by Django 3.2.8 on 2021-10-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abv',
            field=models.FloatField(),
        ),
    ]
