# Generated by Django 2.2.12 on 2021-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211105_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stripe_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
