# Generated by Django 2.2.12 on 2021-11-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211105_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
